Repository EQWorks/react-labs, pull requests merged in 2020-09, with the labels that each got.

#77 [G2M] list - update list item selected colour to primary color
  .gitignore
  src/list/list-item.js
  stories/list.stories.js
Labels: enhancement

#105 [G2M] CHANGELOG - Fix for non-core updates.
  CHANGELOG.md
Labels: documentation

#107 [G2M] Package - Update to version 1.8.0.
  package.json
Labels: enhancement

#115 [G2M] Theme/export
  .storybook/preview.js
  CHANGELOG.md
  src/index.js
Labels: bug

#117 [G2M] CHANGELOG - Update.
  CHANGELOG.md
Labels: documentation

#114 [G2M] Package - Add @material-ui/lab as peer dependency.
  CHANGELOG.md
  README.md
  package.json
Labels: bug

#112 [G2M] Tests/button
  .depcheckrc
  CHANGELOG.md
  __tests__/button/__snapshots__/button.test.js.snap
  __tests__/button/button.test.js
  babel.config.js
  package.json
  src/button.js
  src/typography.js
  stories/button.stories.js
  yarn.lock
Labels: tests

#121 [G2M] Themeprovider/export
  .storybook/preview.js
  CHANGELOG.md
  README.md
  src/index.js
  src/theme/index.js
Labels: enhancement

#122 [G2M] Tests/Alert
  CHANGELOG.md
  __tests__/alert/__snapshots__/alert.test.js.snap
  __tests__/alert/alert.test.js
  __tests__/button/button.test.js
  src/alert.js
  src/theme/index.js
Labels: tests

#128 Deps - Upgrade all minor & patch upgrades. [build]
  package.json
  yarn.lock
Labels: dependencies

#74 [G2M] Fix #68 - Build Chip Component
  CHANGELOG.md
  __mocks__/file-mock.js
  __mocks__/style-mock.js
  __tests__/chip/__snapshots__/chip.test.js.snap
  __tests__/chip/chip.test.js
  __tests__/tests.setup.js
  package.json
  src/chip.js
  src/index.js
  src/theme/overrides/MuiChip.js
  src/theme/overrides/index.js
  src/theme/props.js
  stories/chip.stories.js
Labels: Feature request
